### ISSUE TITLE
support pagination

### ISSUE THREAD

**Issue by iamquan** [willianjusten/cards-jekyll-template#8]
How to paginate post on home page? Thanks

**Comment by willianjusten** [comment]
I don't paginate my blog, but you can follow the [documentation](https://jekyllrb.com/docs/pagination/).
Just define a paginate on your `_config.yaml` and create buttons to next and previous page.

**Comment by iamquan** [comment]
I'm so sorry about digging this issue, but I followed the instruction on documentation to add pagination then I stuck at config the _layouts/default.html. I don't know how to render the paginated posts, and I saw code snippets on documentation, but I wonder how to replace the {{ content }} to render the index.html correctly.

**Comment by willianjusten** [comment]
Paste this line `paginate: 5` on your `_config.yml`.

After that, you have to go to [index.html](https://github.com/willianjusten/cards-jekyll-template/blob/master/index.html#L7), where we create our loop and change to this `{% for post in paginator.posts %}`, 

Then create your pagination code bellow the cards.

```
<!-- Pagination links -->
<div class="pagination">
  {% if paginator.previous_page %}
    <a href="{{ paginator.previous_page_path }}" class="previous">Previous</a>
  {% else %}
    <span class="previous">Previous</span>
  {% endif %}
  <span class="page_number ">Page: {{ paginator.page }} of {{ paginator.total_pages }}</span>
  {% if paginator.next_page %}
    <a href="{{ paginator.next_page_path }}" class="next">Next</a>
  {% else %}
    <span class="next ">Next</span>
  {% endif %}
</div>
```

**Comment by iamquan** [comment]
Thanks, it works :+1: 

Now I want to integrate this improvement https://github.com/timble/jekyll-pagination to have a better pagination display, but I stuck at applying their SCSS. Can you help me? Thanks :smile:

**Comment by willianjusten** [comment]
Hum...I use Stylus for CSS, probably that's the problem... Maybe you could transform the scss into stylus and paste directly into your src folder?

1) Copy the template code from there and paste into the `index.html`
2) Create a `_pagination.styl` into `src/styl` folder and paste all the styles stuff there.

**Comment by iamquan** [comment]
Hi again,

I tried ```gem install sass``` to convert multi scss file into one css file, then I use http://css2stylus.com/ to convert css to stylus, I pasted stylus into _pagination.styl and added ```@import "_pagination"``` in main.styl

I ran ```sudo gulp``` to recompile and it show errors at:

```
    /home/ubuntu/workspace/cards-jekyll-template/src/styl/_pagination.styl:68:28
   64|       &.pages-indicator--active
   65|         display inline-block
   66| 
   67| .pagination .first,
   68| @media (min-width: 320px)   .pagination .last
----------------------------------^
   69|   display inline-block
   70| 
   71| .pagination .pages-indicator--offset-2,

expected "indent", got "media"
```

The whole _pagination.styl contents: 
```
.sr-only
  position absolute
  width 1px
  height 1px
  padding 0
  margin -1px
  overflow hidden
  clip rect(0, 0, 0, 0)
  border 0

.pagination:before, .pagination:after
  content " "
  display table

.pagination
  padding 0
  margin 1em 0
  text-align center
  &:after
    clear both
  li
    display none
    margin 0 0.2em
    padding 0
    list-style none
    .pagination-item
      display block
      speak-number continuous
    &.page
      .pagination-item
        text-decoration none
        width 36px
        height 36px
        border-radius 36px
        line-height 36px
        background #eee
        color #333
        box-shadow inset 0 0 5px rgba(0, 0, 0, 0.05)
      a
        &:hover
          background #ddd
      &.current-page
        .pagination-item
          background #1879CE
          box-shadow inset 0 0 5px rgba(0, 0, 0, 0.3)
          color white
  .previous
    a
      &:before
        content "« "
  .next
    a
      &:after
        content " »"

.pagination .current-page,
.pagination .previous,
.pagination .next
  display inline-block

@media (min-width: 320px)
  .pagination
    .pages-indicator
      &.pages-indicator--active
        display inline-block

.pagination .first,
@media (min-width: 320px)   .pagination .last
  display inline-block

.pagination .pages-indicator--offset-2,
  .pagination .pages-indicator--offset-3,
  .pagination .pages-indicator--offset-4,
  .pagination .pages-indicator--offset-5,
  .pagination .pages-indicator--offset-6,
@media (min-width: 320px)   .pagination .pages-indicator--offset-7
  display inline-block

@media (min-width: 500px)
  .pagination
    .offset-1
      display inline-block
    .pages-indicator--offset-2
      display none

@media (min-width: 600px)
  .pagination
    .offset-2
      display inline-block
    .pages-indicator--offset-3
      display none

@media (min-width: 768px)
  .pagination
    .offset-3
      display inline-block
    .pages-indicator--offset-4
      display none

@media (min-width: 768px)
  .pagination
    .offset-4
      display inline-block
    .pages-indicator--offset-5
      display none

@media (min-width: 768px)
  .pagination
    .offset-5
      display inline-block
    .pages-indicator--offset-6
      display none

@media (min-width: 768px)
  .pagination
    .offset-6
      display inline-block
    .pages-indicator--offset-7
      display none

@media (min-width: 768px)
  .pagination
    .offset-7
      display inline-block
    .pages-indicator--offset-8
      display none

@media (min-width: 768px)
  .pagination
    .offset-8
      display inline-block
    .pages-indicator--offset-9
      display none
```

**Comment by willianjusten** [comment]
Stylus works with indentation, if you have some wrong space, everything will break.
There are a lot of errors with your stylus...

Do this:

Inside your `styl` folder paste this code as `pagination.css` and import in your main, using:

`@import "pagination.css"`, this will work and you don't have to worry with stylus conversion.

```css

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  border: 0;
}

.pagination:before, .pagination:after {
  content: " ";
  display: table;
}
.pagination:after {
  clear: both;
}
.pagination li {
  display: none;
}
.pagination li .pagination-item {
  display: block;
}
.pagination .current-page,
.pagination .previous,
.pagination .next {
  display: inline-block;
}
.pagination .previous a:before {
  content: "« ";
}
.pagination .next a:after {
  content: " »";
}
@media (min-width: 320px) {
  .pagination .pages-indicator.pages-indicator--active {
    display: inline-block;
  }
  .pagination .first,
  .pagination .last {
    display: inline-block;
  }
  .pagination .pages-indicator--offset-2,
  .pagination .pages-indicator--offset-3,
  .pagination .pages-indicator--offset-4,
  .pagination .pages-indicator--offset-5,
  .pagination .pages-indicator--offset-6,
  .pagination .pages-indicator--offset-7 {
    display: inline-block;
  }
}
@media (min-width: 500px) {
  .pagination .offset-1 {
    display: inline-block;
  }
  .pagination .pages-indicator--offset-2 {
    display: none;
  }
}
@media (min-width: 600px) {
  .pagination .offset-2 {
    display: inline-block;
  }
  .pagination .pages-indicator--offset-3 {
    display: none;
  }
}
@media (min-width: 768px) {
  .pagination .offset-3 {
    display: inline-block;
  }
  .pagination .pages-indicator--offset-4 {
    display: none;
  }
}
@media (min-width: 768px) {
  .pagination .offset-4 {
    display: inline-block;
  }
  .pagination .pages-indicator--offset-5 {
    display: none;
  }
}
@media (min-width: 768px) {
  .pagination .offset-5 {
    display: inline-block;
  }
  .pagination .pages-indicator--offset-6 {
    display: none;
  }
}
@media (min-width: 768px) {
  .pagination .offset-6 {
    display: inline-block;
  }
  .pagination .pages-indicator--offset-7 {
    display: none;
  }
}
@media (min-width: 768px) {
  .pagination .offset-7 {
    display: inline-block;
  }
  .pagination .pages-indicator--offset-8 {
    display: none;
  }
}
@media (min-width: 768px) {
  .pagination .offset-8 {
    display: inline-block;
  }
  .pagination .pages-indicator--offset-9 {
    display: none;
  }
}

.pagination {
  padding: 0;
  margin: 1em 0;
  text-align: center;
}
.pagination li {
  margin: 0 0.2em;
  padding: 0;
  list-style: none;
}
.pagination li.page .pagination-item {
  text-decoration: none;
  width: 36px;
  height: 36px;
  border-radius: 36px;
  line-height: 36px;
  background: #eee;
  color: #333;
  box-shadow: inset 0 0 5px rgba(0, 0, 0, 0.05);
}
.pagination li.page a:hover {
  background: #ddd;
}
.pagination li.page.current-page .pagination-item {
  background: #1879CE;
  box-shadow: inset 0 0 5px rgba(0, 0, 0, 0.3);
  color: white;
}
```
